// The Optimize and Export page for "Tab. 10. Optimize and Export" - 完整保留原設計 + SSE 即時版
'use client';

import { useState, useEffect, useRef } from 'react';
import { FiHelpCircle, FiDownload, FiAlertCircle, FiCheckCircle, FiLoader } from 'react-icons/fi';
import { useSchedulingData } from '@/hooks/useSchedulingData';
import { generateYamlFromState } from '@/utils/yamlGenerator';

export default function OptimizeAndExportPage() {
  const {
    apiVersionData,
    descriptionData,
    dateData,
    peopleData,
    shiftTypeData,
    preferences,
    filterAutoGeneratedState
  } = useSchedulingData();

  const [showInstructions, setShowInstructions] = useState(false);
  const [apiEndpoint, setApiEndpoint] = useState(process.env.BACKEND_API_URL || 'http://localhost:8000');
  const [prettifyArg, setPrettifyArg] = useState(true);
  const [timeoutArg, setTimeoutArg] = useState<number>(300);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [scheduleFilename, setScheduleFilename] = useState<string | null>(null);
  const [scheduleScore, setScheduleScore] = useState<string | null>(null);
  const [scheduleStatus, setScheduleStatus] = useState<string | null>(null);

  // SSE 相關
  const [logs, setLogs] = useState<string>('');
  const logsEndRef = useRef<HTMLDivElement>(null);
  const eventSourceRef = useRef<EventSource | null>(null);
  const currentTaskId = useRef<string | null>(null);
  const [isTaskFinished, setIsTaskFinished] = useState(false);
  const instructions = [
    "This page sends your current scheduling configuration to the optimization server",
    "The server will compute an optimal schedule and return an Excel (.xlsx) file",
    "Configure optimization options (prettify and timeout) before submitting",
    "Prettify: Enables prettier output formatting in the generated schedule",
    "Timeout: Maximum time (in seconds) the optimizer will run before stopping",
    "Click 'Optimize and Download' to generate your schedule",
    "The optimization score and status will be displayed after completion",
    "Real-time logs are shown below during optimization"
  ];

  const filteredState = filterAutoGeneratedState({
    apiVersion: apiVersionData,
    description: descriptionData,
    dates: dateData,
    people: peopleData,
    shiftTypes: shiftTypeData,
    preferences
  });

  const currentYaml = generateYamlFromState(filteredState);

  // 自動滾動
  useEffect(() => {
    logsEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [logs]);

  // 清理舊 SSE
  useEffect(() => {
    return () => {
      if (eventSourceRef.current) {
        eventSourceRef.current.close();
      }
    };
  }, []);

  async function checkAndDownload(taskId: string, apiEndpoint: string, setLogs: React.Dispatch<React.SetStateAction<string>>) {
  try {
    const dlRes = await fetch(`${apiEndpoint}/task/${taskId}/download`);

    const contentType = dlRes.headers.get('content-type') || '';

    // === 情況 1：後端回 JSON，代表檔案還沒準備好 ===
    if (contentType.includes('application/json')) {
      const data = await dlRes.json().catch(() => null);

      if (!dlRes.ok || (data && data.ready === false)) {
        setLogs((prev: string) => prev + "\n⚠️ 檔案尚未產生，請稍後重新試。\n");
        return;
      }
    }

    // === 情況 2：後端回 Excel Blob ===
    if (!dlRes.ok) {
      setLogs((prev: string) => prev + "\n❌ 下載發生錯誤（後端回傳非 200）。\n");
      return;
    }

    const blob = await dlRes.blob();
    const url = window.URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    let filename = "schedule.xlsx";
    const disposition = dlRes.headers.get("content-disposition");

    if (disposition && disposition.includes("filename=")) {
      const match = disposition.match(/filename="?([^"]+)"?/);
      if (match && match[1]) {
        filename = match[1];
      }
    }

    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();

    window.URL.revokeObjectURL(url);
    setLogs((prev: string) => prev + "\n📥 檔案下載完成！\n");

  } catch {
    setLogs((prev: string) => prev + "\n❌ 下載發生錯誤（JS Exception）。\n");
  }
}

  const handleOptimizeAndDownload = async () => {
    setIsLoading(true);
    setErrorMessage(null);
    setSuccessMessage(null);
    setScheduleFilename(null);
    setScheduleScore(null);
    setScheduleStatus(null);
    setLogs('正在啟動優化任務...\n');

    // 關閉舊連線
    if (eventSourceRef.current) {
      eventSourceRef.current.close();
      eventSourceRef.current = null;
    }

    try {
      const formData = new FormData();
      formData.append('yaml_content', currentYaml);
      if (prettifyArg) formData.append('prettify', 'true');
      formData.append('timeout', timeoutArg.toString());

      const response = await fetch(`${apiEndpoint}/start-optimization`, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        const err = await response.text();
        throw new Error(err || `HTTP ${response.status}`);
      }

      const { task_id } = await response.json();
      currentTaskId.current = task_id;
      setLogs(prev => prev + `任務啟動成功！ID: ${task_id.slice(0, 8)}\n連線即時日誌...\n\n`);

      const evtSource = new EventSource(`${apiEndpoint}/task/${task_id}/logs`);
      eventSourceRef.current = evtSource;

      evtSource.onmessage = (event) => {
        const data = event.data.trim();
        if (data === 'DONE') {
          evtSource.close();
          eventSourceRef.current = null;

          setIsLoading(false);
          setIsTaskFinished(true);
          setLogs(prev => prev + "\n=== 任務完成 ===\n");

          if (currentTaskId.current) {
            checkAndDownload(currentTaskId.current, apiEndpoint, setLogs);
          }

          return;
        }

        setLogs(prev => prev + data + '\n');

        // 自動解析後端傳的關鍵資訊
        if (data.includes('最終分數') || data.includes('Score =')) {
          const match = data.match(/\d+/);
          if (match) setScheduleScore(match[0]);
        }
        if (data.includes('狀態') || data.includes('Status')) {
          const match = data.match(/(OPTIMAL|FEASIBLE|INFEASIBLE.*)/i);
          if (match) setScheduleStatus(match[1]);
        }
        if (data.includes('.xlsx')) {
          const match = data.match(/nurse-scheduling[^ \n]*/);
          if (match) {
            setScheduleFilename(match[0]);
            setSuccessMessage('Schedule optimized and downloaded successfully!');
          }
        }
      };

      evtSource.onerror = () => {
        evtSource.close();
        eventSourceRef.current = null;
        setLogs(prev => prev + '\n後端連線中斷');
        setErrorMessage('連線中斷，請檢查後端是否正常運行');
        setIsLoading(false);
      };

    } catch (error: unknown) {
      if (error instanceof Error) {
      setErrorMessage(error.message);
    } else {
      setErrorMessage('啟動失敗');
    }
    setIsLoading(false);
      }
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
        <div className="flex items-center gap-3">
          <h1 className="text-3xl font-bold text-gray-800">Optimize and Export</h1>
          {instructions.length > 0 && (
            <button
              onClick={() => setShowInstructions(!showInstructions)}
              className="text-gray-500 hover:text-gray-700 transition-colors"
              title="Toggle instructions"
            >
              <FiHelpCircle className="h-6 w-6" />
            </button>
          )}
        </div>
      </div>

      {showInstructions && (
        <div className="mb-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-blue-800 mb-3">Instructions</h3>
          <ul className="space-y-2 text-sm text-blue-700">
            {instructions.map((instruction, index) => (
              <li key={index}>• {instruction}</li>
            ))}
          </ul>
        </div>
      )}
      <div className="mb-6 bg-amber-50 border border-amber-200 rounded-lg p-4">
        <h3 className="text-lg font-medium text-amber-800 mb-3 flex items-center gap-2">
          <FiAlertCircle className="h-5 w-5" />
          Warning
        </h3>
        <div className="space-y-2 text-sm text-amber-700">
          <p>
            Make sure the FastAPI server is running on the configured endpoint: {apiEndpoint}.
            You can start the server with: <code className="bg-amber-100 px-1 py-0.5 rounded">fastapi dev core/nurse_scheduling/serve.py</code>
          </p>
        </div>
      </div>

      {/* Error */}
      {errorMessage && (
        <div className="mb-6 bg-red-50 border border-red-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-red-800 mb-2 flex items-center gap-2">
            <FiAlertCircle className="h-5 w-5" />
            Error
          </h3>
          <p className="text-sm text-red-700">{errorMessage}</p>
        </div>
      )}

      {/* Success */}
      {successMessage && (
        <div className="mb-6 bg-green-50 border border-green-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-green-800 mb-2 flex items-center gap-2">
            <FiCheckCircle className="h-5 w-5" />
            Success
          </h3>
          <p className="text-sm text-green-700">{successMessage}</p>
          {scheduleFilename && (
            <p className="text-sm text-green-700 mt-2">
              <strong>File:</strong>{' '}
              <a href={`${apiEndpoint}/task/${currentTaskId.current}/download`} download className="underline">
                {scheduleFilename}
              </a>
            </p>
          )}
          {scheduleScore && (
            <p className="text-sm text-green-700">
              <strong>Score:</strong> {scheduleScore}
            </p>
          )}
          {scheduleStatus && (
            <p className="text-sm text-green-700">
              <strong>Status:</strong> {scheduleStatus}
            </p>
          )}
        </div>
      )}

      <div className="bg-white shadow-md rounded-lg overflow-hidden mb-6">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800">Optimization Settings</h3>
        </div>

        <div className="p-6 space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              API Endpoint
            </label>
            <input
              type="text"
              value={apiEndpoint}
              onChange={(e) => setApiEndpoint(e.target.value)}
              className="block w-full px-4 py-2 text-sm text-gray-900 bg-white border border-gray-300 rounded-lg shadow-sm transition-colors duration-200 ease-in-out focus:border-blue-500 focus:ring-blue-200 placeholder-gray-400 focus:outline-none focus:ring-2 hover:border-gray-400"
              placeholder="http://localhost:8000"
            />
            <p className="mt-1 text-sm text-gray-500">
              URL of the backend scheduling server
            </p>
          </div>

          <div className="flex items-center gap-4">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={prettifyArg}
                onChange={(e) => setPrettifyArg(e.target.checked)}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <span className="text-sm font-medium text-gray-700">
                Enable Prettify
              </span>
            </label>
            <span className="text-sm text-gray-500">
              (Prettier output formatting in generated schedule)
            </span>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Timeout (seconds)
            </label>
            <input
              type="number"
              value={timeoutArg}
              onChange={(e) => setTimeoutArg(parseInt(e.target.value) || 300)}
              min="1"
              max="3600"
              className="block w-full px-4 py-2 text-sm text-gray-900 bg-white border border-gray-300 rounded-lg shadow-sm transition-colors duration-200 ease-in-out focus:border-blue-500 focus:ring-blue-200 placeholder-gray-400 focus:outline-none focus:ring-2 hover:border-gray-400"
            />
            <p className="mt-1 text-sm text-gray-500">
              Maximum time the optimizer will run (1-3600 seconds)
            </p>
          </div>

          <div className="flex justify-end">
            <button
              onClick={handleOptimizeAndDownload}
              disabled={isLoading}
              className={`flex items-center gap-2 px-6 py-2 font-medium rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 ${
                isLoading
                  ? 'bg-gray-400 cursor-not-allowed text-white'
                  : 'bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500'
              }`}
            >
              {isLoading ? (
                <>
                  <FiLoader className="h-5 w-5 animate-spin" />
                  Optimizing...
                </>
              ) : (
                <>
                  <FiDownload className="h-5 w-5" />
                  Optimize and Download
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* 新增即時log */}
      {(isLoading || isTaskFinished) && (
        <div className="mb-6 bg-gray-900 text-green-400 rounded-lg shadow-xl overflow-hidden">
          <div className="px-6 py-4 bg-gray-800 flex items-center justify-between">
            <h3 className="text-lg font-bold">即時優化日誌</h3>
            {isLoading ? (
              <FiLoader className="animate-spin h-5 w-5" />
            ) : isTaskFinished ? (
              <span className="text-green-400 font-semibold">✔ 已完成</span>
            ) : null}
          </div>
          <pre className="p-6 h-96 overflow-auto font-mono text-sm leading-snug">
            {logs}
            <div ref={logsEndRef} />
          </pre>
        </div>
      )}

      <div className="bg-white shadow-md rounded-lg overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800">YAML Preview</h3>
          <p className="text-sm text-gray-600 mt-1">
            This is the configuration that will be sent to the optimization server
          </p>
        </div>

        <div className="relative">
          <pre
            className="w-full h-96 p-4 font-mono text-sm overflow-auto bg-gray-50 whitespace-pre-wrap"
            style={{ fontFamily: 'ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace' }}
          >
            {currentYaml}
          </pre>
        </div>
      </div>
    </div>
  );
}